name: atendi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  jitsi_meet_flutter_sdk: ^10.3.0
  mobile_scanner: ^6.0.2
  qr_flutter: ^4.1.0  
  camera: ^0.10.6
  sqflite: ^2.3.0
  uuid: ^3.0.7
  path: ^1.8.3
  path_provider: ^2.0.15
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
